import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";
import { defineConfig, globalIgnores } from "eslint/config";

// eslint-config-next@15 still ships legacy eslintrc objects
// (`module.exports = { extends: [...] }`), not flat config arrays — so they
// cannot be imported and spread directly. FlatCompat translates them. Once this
// project moves to eslint-config-next@16+, which exports flat config natively,
// this can collapse back to a plain `import nextVitals from
// "eslint-config-next/core-web-vitals"` and a spread.
const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const eslintConfig = defineConfig([
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  globalIgnores([
    ".next/**",
    // `npm run build:verify` writes here. `npm run lint` is a bare `eslint`, so
    // it walks the cwd and will happily lint a build output directory unless it
    // is named — 374 phantom errors from generated chunks, and one real warning
    // buried under them.
    ".next-verify/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by drizzle-kit; not ours to lint.
    "drizzle/**",
  ]),
]);

export default eslintConfig;
